version: '3.1'

services:
  backend:
    build: backend
    restart: always
    env_file:
      - variables.env
    networks:
      - angular-spring
      - spring-mysql
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - variables.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - spring-mysql

  frontend:
    build:
      context: frontend
    ports:
      - 4200:4200
      - 80:80
    environment:
      - BASE_URL_BACKEND=backend
    networks:
      - angular-spring
    depends_on:
      - backend
    expose:
      - 4200
      - 42000 
      - 80

networks:
  angular-spring: {}
  spring-mysql: {}
